// TODO: make an express server for this
export default [
  { firstName: 'Brandon',
    lastName: 'Day',
    parent1: '',
    parent2: '',
    id: 5,
    special: '3221211'},
  { firstName: 'Christopher',
    lastName: 'Sutton',
    parent1: '',
    parent2: '',
    id: 4,
    special: '2121222'},
  { firstName: 'Peter',
    lastName: 'Lee',
    parent1: '',
    parent2: '',
    id: 6,
    special: '2221212'},
  { firstName: 'George',
    lastName: 'Lewis',
    parent1: '',
    parent2: '',
    id: 1,
    special: '5121121'},
    // end electric
  { firstName: 'Julia',
    lastName: 'Baker',
    id: 2,
    special: '2222112'},
  { firstName: 'Patrick',
    lastName: 'Stewart',
    id: 3,
    special: '2122221'},
  { firstName: 'William',
    lastName: 'Jackson',
    id: 7,
    special: '1222212'},
  { firstName: 'Julie',
    lastName: 'Fox',
    id: 8,
    special: '1512211'},
  //end water room
  { firstName: 'Frank',
    lastName: 'Bowman',
    id: 9,
    special: '3122121'},
  { firstName: 'Kayla',
    lastName: 'Thompson',
    id: 10,
    special: '1222122'},
  { firstName: 'Helen',
    lastName: 'Harvey',
    id: 11,
    special: '2211231'},
  { firstName: 'Cynthia',
    lastName: 'Miller',
    id: 12,
    special: '1221151'},
  { firstName: 'Nicole',
    lastName: 'Prat',
    id: 13,
    special: '2122122'},
  { firstName: 'Greg',
    lastName: 'Lewis',
    parent1: 13,
    parent2: 1,
    id: 15,
    special: '1213212'},
  { firstName: 'Dylan',
    lastName: 'Ward',
    id: 14,
    special: ''},
    //TODO: add parents to Kyle Stewart's profile
  { firstName: 'Kyle',
    lastName: 'Stewart',
    parent1: 12,
    parent2: 3,
    id: 16,
    special: '1223112'},
  { firstName: 'Tiffany',
    lastName: 'Fox',
    parent1: 8,
    parent2: 7,
    id: 17,
    special: '2123112'},
  { firstName: 'Joan',
    lastName: 'Stewart',
    parent1: 8,
    parent2: 7,
    id: 18,
    special: '2321121'},
]
